name: CI/CD Pipeline

on:
  push:
    branches:
      - master   # Jalan otomatis setiap push ke master

jobs:
  test_code:
    name: üß™ Test Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install beautifulsoup4

      - name: Run unit tests
        run: python unit-test.py


  deploy:
    name: üöÄ Deploy to EC2
    runs-on: ubuntu-latest
    needs: test_code  # Deploy hanya jalan kalau test_code sukses
    environment:
      name: production

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install SSH client
        run: sudo apt-get update && sudo apt-get install -y openssh-client

      - name: üîê Setup SSH & Deploy
        env:
          DEPLOY_SERVER: ${{ secrets.DEPLOY_SERVER_IP }}
          DEPLOY_USER: ${{ secrets.DEPLOY_USER_UBUNTU }}
          SSH_KEY: ${{ secrets.SSH_KEY_UBUNTU }}
        run: |
          echo "üöÄ Starting automatic deployment to EC2..."

          mkdir -p ~/.ssh
          ssh-keyscan -t rsa $DEPLOY_SERVER >> ~/.ssh/known_hosts
          echo "$SSH_KEY" | tr -d '\r' > temp_key
          chmod 600 temp_key

          scp -i temp_key deploy.sh $DEPLOY_USER@$DEPLOY_SERVER:/tmp/deploy.sh
          ssh -i temp_key $DEPLOY_USER@$DEPLOY_SERVER "
            echo 'üí° Running deploy.sh on EC2...'
            chmod +x /tmp/deploy.sh
            bash /tmp/deploy.sh

            echo '‚è≥ Waiting 45s for Grafana/Prometheus stability...'
            sleep 45

            cd /home/ubuntu/myapp || exit 1
            echo '‚öôÔ∏è Importing Grafana dashboard...'
            chmod +x complete-dashboard.sh
            ./complete-dashboard.sh

            echo '‚úÖ Deployment and Monitoring Setup Complete!'
          "

          echo "‚úÖ DEPLOYMENT SUCCESSFUL!"
